CREATE DATABASE SchoolDB;
USE SchoolDB;

CREATE TABLE Students (
StudentID INT AUTO_INCREMENT PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
BirthDate DATE NOT NULL,
Email VARCHAR(100) UNIQUE
);

CREATE TABLE Departments (
    DepartmentID INT AUTO_INCREMENT PRIMARY KEY,
    DepartmentName VARCHAR(100) UNIQUE NOT NULL,
    OfficeLocation VARCHAR(50) NULL
);

CREATE TABLE Courses (
    CourseID INT AUTO_INCREMENT PRIMARY KEY,
    CourseName VARCHAR(100) NOT NULL,
    Units TINYINT UNSIGNED NOT NULL,
    DepartmentID INT,
    FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID)
);

CREATE TABLE Faculty (
FacultyID INT AUTO_INCREMENT PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
DepartmentID INT,
FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID),
Email VARCHAR(100) UNIQUE
);

CREATE TABLE Enrollments (
EnrollmentID INT AUTO_INCREMENT PRIMARY KEY,
StudentID INT, FOREIGN KEY(StudentID) REFERENCES Students(StudentID),
CourseID INT, FOREIGN KEY(CourseID) REFERENCES Courses(CourseID),
Semester ENUM('1', '2', 'Summer') NOT NULL,
AcademicYear VARCHAR(9) NOT NULL,
Grade DECIMAL(3,2) NULL
);

ALTER TABLE Students
ADD Gender ENUM('M', 'F') NOT NULL;

ALTER TABLE Students
MODIFY Email VARCHAR(100) UNIQUE NULL;

ALTER TABLE Faculty
MODIFY Email VARCHAR(100) UNIQUE NULL;

ALTER TABLE Students 
CHANGE LastName FamilyName VARCHAR(50) NOT NULL;

ALTER TABLE Faculty
CHANGE LastName FamilyName VARCHAR(50) NOT NULL;
